### PR TITLE
add github action strategy matrix to run compilation & test for all supported scala versions

### PR DESCRIPTION
**Pull request by tribbloid**
voila, also publish the testing result for each scala minor version

this is blocking a patch for scala 2.13.6+ and scala 2.12.14+

### CODE REVIEW

**Comment by tek** [comment]
nice!

**Comment by tribbloid** [comment]
Any plan for 2.13.6+ after SplainFormatter became part of Scala? It should be included in the next release with 2.12.14 support (which is easy)

**Comment by tek** [comment]
I'd say to start we can just release an empty plugin for 2.13.6. The AnalyzerPlugin method shouldn't be hard to implement, but I'd say it's not vital that it's immediately available.
And if there are no new features, we don't even have to version bump for 2.12.14, just doing `++2.12.13 publish; sonatypePublishAll` should be fine

**Comment by tribbloid** [comment]
Are you sure? If we do this people will get compilation bug on 2.12.14 (the latest version supported by Spark & Flink). One of them is already complaining here

**Comment by tek** [comment]
I typoed the version there – I meant we can release the old version for 2.12.14, I do that all the time

**Comment by tribbloid** [comment]
make sense, will push the patch shortly, would you like to accept this PR?

**Pull request merged**
