### PR TITLE
enable scalafmt 2.7.5 & its sbt plugin with default formatting

### PR DESCRIPTION
**Pull request by tribbloid**
this allows committers to work together without causing conflicts due to format differences.

Default format with no config  at the moment. Please tell me your preferences

I can almost predict that you have a .NET background :)

### CODE REVIEW

**Comment by tek** [comment]
I don't, I format code solely based on what's efficient to edit with vim :smile: 

I guess this is reasonable, I'll have a look at the scalafmt config docs, it seems to be quite extensive

**Comment by tribbloid** [comment]
any update?

**Comment by tek** [comment]
I took a deep dive into the options page and this is what I came up with:

```
maxColumn = 120
continuationIndent.defnSite = 2
continuationIndent.extendSite = 0
align.preset = none
align.tokens = []
align.openParenCallSite = false
align.openParenDefnSite = false
newlines.beforeMultiline = unfold
newlines.beforeMultilineDef = unfold
rewrite.rules = [AvoidInfix, RedundantBraces, RedundantParens]
rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.ifElseExpressions = true
trailingCommas = always
includeNoParensInSelectChains = true
```

**Comment by tribbloid** [comment]
sounds good! updated. Still a lot of changes tho

**Comment by tek** [comment]
guess that's to be expected. but I like it! thanks a lot

**Pull request merged**
