### PR TITLE
first draft for diverging implicit splanation. Recommended to integrate ASAP to engage test users

### PR DESCRIPTION
**Pull request by tribbloid**
voila

### CODE REVIEW

**Comment by tribbloid** [comment]
@tek errr. I don't know how to do this. Is it possible to add new settings called `Vimplicit-diverging` under `global.settings`? Or we have to write our own parser?

**Comment by tek** [comment]
did we have a pressing reason for entirely removing configuration via `-P:splain` parameters?

**Comment by tribbloid** [comment]
@tek  good idea, resubmitted, which enabled the following 2 parameters:

```
    val implicitDiverging = "Vimplicits-diverging"

    val implicitDivergingMaxDepth = "Vimplicits-diverging-max-depth"
```

enabled by "-P:splain:Vxxxx"

**Comment by tribbloid** [comment]
The max-depth was added in fear of breaking the implicit search algorithm

**Comment by tribbloid** [comment]
Could you review and approve it again? Looks good on CI

**Comment by tek** [comment]
ship it!

**Pull request merged**
