### PR TITLE
2.12.14 support

### PR DESCRIPTION
**Pull request by tribbloid**
add a new profile before/after scala 2.12.14/2.13.6

### CODE REVIEW

**Comment by tek** [comment]
is it ok that those tests fail?

**Comment by tribbloid** [comment]
Sorry, they are NOT ok, just found that the new method still causes WrongMethodTypeException

PLEASE HOLD ON

**Comment by tribbloid** [comment]
Turns out that WrongMethodTypeException is a sub-optimal implementation of asInstanceOf[.] method. It is not inlined as in Java's `(boolean)` cast. At the moment I only saw 2 options:

1. set `areSomeColdStatsEnabled` to be always true, if it doesn't impact performance a lot
2. create a `java_2.13.6+` directory

**Comment by tribbloid** [comment]
circumvented by using `invoke` instead of `invokeExact`, not the test should compile successfully

I have no idea man, this is supposed to be fixed by https://github.com/scala/scala/pull/4139, it should probably be reopened

anyway not of my concern

**Comment by tribbloid** [comment]
May I ask a question?

Is there a downside of including "scalaVersion" in the "crossScalaVersion"? E.g.:

```
scalaVersion := "2.13.5"
crossScalaVersions ++= List(
  "2.13.5",
  "2.13.4",
  "2.13.3",
  "2.13.2",
  "2.13.1",
  "2.12.6",
  "2.12.7",
  "2.12.8",
  "2.12.9",
  "2.12.10",
  "2.12.11",
  "2.12.12",
  "2.12.13",
  "2.12.14",
)
```

It is easier to debug this way

**Comment by tek** [comment]
not sure, does it run commands twice with `+compile` or something? otherwise I wouldn't see why this should be a problem

**Review by tek — APPROVED** [review]

**Comment by tribbloid** [comment]
No it doesn't!

```
~/git/shapesafe/splain$ sbt +compile > log.log

~/git/shapesafe/splain$ cat log.log | grep "Forcing Scala version to"
[info] Forcing Scala version to 2.12.10 on all projects.
[info] Forcing Scala version to 2.12.11 on all projects.
[info] Forcing Scala version to 2.12.12 on all projects.
[info] Forcing Scala version to 2.12.13 on all projects.
[info] Forcing Scala version to 2.12.14 on all projects.
[info] Forcing Scala version to 2.12.6 on all projects.
[info] Forcing Scala version to 2.12.7 on all projects.
[info] Forcing Scala version to 2.12.8 on all projects.
[info] Forcing Scala version to 2.12.9 on all projects.
[info] Forcing Scala version to 2.13.1 on all projects.
[info] Forcing Scala version to 2.13.2 on all projects.
[info] Forcing Scala version to 2.13.3 on all projects.
[info] Forcing Scala version to 2.13.4 on all projects.
[info] Forcing Scala version to 2.13.5 on all projects.
```

**Comment by tribbloid** [comment]
will be squeezed into the next PR, let's close it

**Comment by tek** [comment]
wonderful

**Comment by tek** [comment]
please tell me when it's ready to be pushed to Maven

**Comment by tribbloid** [comment]
should be ready by now, not sure if we should use a new patch version number (as we have some improvements on singleton & and ZIO types)

**Comment by tek** [comment]
oh, right, there are new features. definitely then. I shall make a new release now

**Comment by tek** [comment]
wait, we don't have a dummy plugin for 2.13.6 yet

**Comment by tribbloid** [comment]
... or a working plugin :) those improvements on singleton & and ZIO types are also not in the 2.13.6 compiler

**Comment by tek** [comment]
alright then. I've started experimenting with the analyzer plugin back in the day, I'll see if I can unearth something useful

**Comment by tek** [comment]
Btw, I backported the singleton and zlayer stuff to the compiler in the end. Are you referring to improvements made _on_ those features or the features themselves?

In any case, since I didn't add a plugin hook for type mismatch, we're only called for implicit errors. I should create another PR with an additional hook, but the first one was already met with a bit of suspicion.

**Comment by tribbloid** [comment]
I mean the features themselves (improvement can be slow). Sounds like an alternative if the analyser plugin takes too much work

**Comment by tek** [comment]
well then, those are in 2.13.6. the zlayer test shows some additional line breaks, but otherwise they all pass

**Pull request merged**
