### PR TITLE
Build for 2.13.0 and 2.12.9

### PR DESCRIPTION
**Pull request by Doikor**

### CODE REVIEW

**Comment by tek** [comment]
thanks. FYI 2.13 has been released for a while, see https://repo1.maven.org/maven2/io/tryp/splain_2.13.0/0.4.1/. Appears I forgot to push

**Comment by tek** [comment]
2.12.9 now released.

**Comment by Doikor** [comment]
Doesn't look like the `2.12.9` version successfully published itself?

```
[error]   Not found
[error]   not found: /Users/Doikor/.ivy2/local/io.tryp/splain_2.12.9/0.4.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/tryp/splain_2.12.9/0.4.1/splain_2.12.9-0.4.1.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/io/tryp/splain_2.12.9/0.4.1/splain_2.12.9-0.4.1.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:226)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$31(CoursierDependencyResolution.scala:195)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:195)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2843)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading io.tryp:splain_2.12.9:0.4.1
[error]   Not found
[error]   not found: /Users/Doikor/.ivy2/local/io.tryp/splain_2.12.9/0.4.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/tryp/splain_2.12.9/0.4.1/splain_2.12.9-0.4.1.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/io/tryp/splain_2.12.9/0.4.1/splain_2.12.9-0.4.1.pom
[error] Total time: 2 s, completed 12 Aug 2019, 16.29.19
```

**Comment by tek** [comment]
indeed, there was a failure during promotion. will look into it.

**Comment by tek** [comment]
seems to be there now!

**Pull request closed without merging**
