### PR TITLE
Add 2.12.14

### PR DESCRIPTION
**Pull request by ithinkicancode**

### CODE REVIEW

**Comment by tek** [comment]
thanks :purple_heart:

**Comment by tek** [comment]
@tribbloid there seem to be some issues that look like they're related to your latest commit, can you take a look?

**Comment by tribbloid** [comment]
absolutely. I assume they only manifests on 2.12.14

**Comment by tek** [comment]
yeah, something in that Statistics object was removed

**Comment by tribbloid** [comment]
I encounter the same problem in 2.13.6, but 2.13.6+ should use the new architecture (https://github.com/tek/splain/issues/53). So I ignored it.

We will need a new shim layer, this is not caused by my change but I'll make it work

**Comment by tek** [comment]
great, thanks!

**Comment by tribbloid** [comment]
BTW @ithinkicancode this one is on us: our CI doesn't have cross-build pipelines yet

But it's better if you run sbt `+ compile` to make sure that it at least compiles

**Pull request merged**
