### PR TITLE
#76 all tests for scala 2.13.7 works now

### PR DESCRIPTION
**Pull request by tribbloid**
The patch also change the runtime compilation engine (from scala macro to scala NSC) and improve implicit error tree compact display

### CODE REVIEW

**Comment by tribbloid** [comment]
I would recommend the release of 1.0.0-RC2 immediately before the end of 2021

**Review by tek — APPROVED** [review]

**Comment by tek** [comment]
that's a lot of changes :sweat_smile:

**Comment by tribbloid** [comment]
Sorry I made a few typos. Won't rush for end of year (bad things happen to people who can't wait)

Most changes are for cross-versioning. Many of them are directly copied from Scala partest.

But some ground truths are indeed different. The biggest one is for compact implicit tree:

**** BEFORE

```
newSource1.scala:28: error: implicit error;
!I e: tpes.I1
i1a invalid because
!I p: tpes.I2
⋮
――――――――i8 invalid because
        !I p: tpes.I9
――――i6b invalid because
    !I p: tpes.I8
――――――i8 invalid because
      !I p: tpes.I9
――i3b invalid because
  !I p: tpes.I4
  ⋮
――――――――i8 invalid because
        !I p: tpes.I9
――――i6b invalid because
    !I p: tpes.I8
――――――i8 invalid because
      !I p: tpes.I9
i1b invalid because
!I p: tpes.I6
  ⋮
――――――i8 invalid because
      !I p: tpes.I9
――i6b invalid because
  !I p: tpes.I8
――――i8 invalid because
    !I p: tpes.I9
  implicitly[I1]
            ^
```

**** AFTER: now it shows the causes of every implicit error if number of these causes >=2

```
newSource1.scala:28: error: implicit error;
!I e: tpes.I1
i1a invalid because
!I p: tpes.I2
⋮
――i3a invalid because
  !I p: tpes.I4
  ⋮
――――i6a invalid because
    !I p: tpes.I7
    ⋮
――――――――i8 invalid because
        !I p: tpes.I9
――――i6b invalid because
    !I p: tpes.I8
――――――i8 invalid because
      !I p: tpes.I9
――i3b invalid because
  !I p: tpes.I4
  ⋮
――――i6a invalid because
    !I p: tpes.I7
    ⋮
――――――――i8 invalid because
        !I p: tpes.I9
――――i6b invalid because
    !I p: tpes.I8
――――――i8 invalid because
      !I p: tpes.I9
i1b invalid because
!I p: tpes.I6
――i6a invalid because
  !I p: tpes.I7
  ⋮
――――――i8 invalid because
      !I p: tpes.I9
――i6b invalid because
  !I p: tpes.I8
――――i8 invalid because
    !I p: tpes.I9
  implicitly[I1]
            ^
```

This test case only affects compact mode (WITHOUT -VImplicit-verbose-tree). So it was omitted in both Scala project & splain. The patch added it back

**Comment by tek** [comment]
cool!

**Pull request merged**
