### PR TITLE
file structure of most classes are now compliant with JVM language standard

### PR DESCRIPTION
**Pull request by tribbloid**
file structure of most classes are now compliant with JVM language standard:

- source that declared a package must be in a directory of corresponding path

- most source now contains only 1 class: this is not necessary but will make indexing of most IDE faster

BTW: are you using any CI service? Have you considered enabling github action that run the test everytime a patch has been submitted?

### CODE REVIEW

**Review by tek — APPROVED** [review]

**Comment by tek** [comment]
added you as a collaborator, go wild with the github actions!

**Comment by tribbloid** [comment]
roger roger, sorry I was a bit slacking due to other projects. The actions should be easy tho

**Comment by tek** [comment]
no pressure, just thought you might be waiting for me to merge it

**Comment by tribbloid** [comment]
OK I've finally done. The CI is online: https://github.com/tribbloid/splain/runs/2592505496?check_suite_focus=true

Just ping me to approve the merge

**Comment by tek** [comment]
awesome, go ahead!

did you see that the compiler PR was merged?

**Comment by tribbloid** [comment]
Yeah, and the ZIO patch, thanks a lot!

There seems to be a problem of my collaborator's permission:

```
[splain] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/#43/tree:#43/tree
remote: Permission to tek/splain.git denied to tribbloid.
fatal: unable to access 'https://github.com/tek/splain/': The requested URL returned error: 403
```

Can you double check if I'm in the group?

**Comment by tek** [comment]
the problem is that you haven't accepted the invite! I'll see if I can resend it

**Comment by tribbloid** [comment]
I see, sorry don't know it expires. Using my permission now ...

https://github.com/tek/splain/actions/runs/847753214

**Comment by tek** [comment]
yay! :partying_face:

**Pull request closed without merging**
